baseURL: https://cvbioinfoufmg.github.io/
languageCode: pt-br
title: Curso de Verão em Bioinformática da UFMG
themesDir: themes/
theme: villain
publishDir: docs/

params:
  colors:
    background_color: "#eff4ef"
    black: "#8a7a50"
    primary_color: "#37505a"
    secondary_color: "#83a0a6"
  homepage_meta_tags:
    meta_description: "Bem-vindos ao Curso de Verão em Bioinformática da Universidade Federal de Minas Gerais. Nos sigam e fiquem de olho em todas as novidades."
    meta_og_title: "Curso de Verão em Bioinformática da UFMG"
    meta_og_url: https://cvbioinfoufmg.github.io
    meta_og_image: https://raw.githubusercontent.com/cvbioinfoufmg/cvbioinfoufmg.github.io/master/static/header/cvbioingoufmg-twitter-banner.png
    meta_twitter_card: summary_large_image
    meta_twitter_site: "@cvbioinfoufmg"
    meta_twitter_creator: "@luciorqueiroz"
  google_analytics_id: UA-108812139-3

menu:
  main:
  - identifier: Home
    name: "~/"
    url: /home/
    weight: 1
  - identifier: ppg
    name: Pós-graduação em Bioinformática na UFMG
    url: /program/
    weight: 2
  - identifier: inscricoes
    name: Inscrições
    url: /registration/
    weight: 3
  - identifier: edicoes
    name: Edições
    url: /edition/
    weight: 4
  - identifier: sobre
    name: Sobre nós
    url: /about/
    weight: 5


# Needed for mermaid/katex shortcodes and Rmd
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

ignoreFiles:
  ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
